// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "mongo"
		digest:     ""
		tag:        "4.2.23"
	}
}
