// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/mmorejon/cinema-showtimes"
		digest:     "sha256:70d087aaf0e888310cfb585eb81e308721e38bb96819e2908358131be1fc2dc8"
		tag:        "v2.2.2"
	}
}
