// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/mmorejon/cinema-users"
		digest:     "sha256:3a1e8fd1f3cb832981bcadb3fff056eb0a2300cf7cb6bf94460c6bccdd6743ed"
		tag:        "v2.2.2"
	}
}
