// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/mmorejon/cinema-movies"
		digest:     "sha256:6f15801d3fa8fbfa58b6718851c28841e010935c205b5770c7deb949fc2e2e25"
		tag:        "v2.2.2"
	}
}
