// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/mmorejon/cinema-website"
		digest:     "sha256:ba1873a0616cb0bc6b0bf4a109e8e569438cc28b89512cfbf63b093650c132bf"
		tag:        "v2.2.2"
	}
}
