// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

package main

// Defaults
values: {
	image: {
		repository: "ghcr.io/mmorejon/cinema-bookings"
		digest:     "sha256:9b51714509861b1dad066f56f1c1e5387f20828b113c6d557761fa5b11eef858"
		tag:        "v2.2.2"
	}
}
